using './ChatbotAppService.bicep'

param appServiceName = 'chatbot-prod-001'
param appServicePlanName = 'plan-chatbot-prod-001'
param location = 'East US'
param appServicePlanSku = 'P1v3'
param dockerRegistryServerUrl = 'https://index.docker.io'
param dockerRegistryServerUsername = ''
param dockerRegistryServerPassword = ''
param mainAppImage = 'node:18-alpine'
param llmSidecarImage = 'ollama/ollama:latest'
param environment = 'prod'