using './ChatbotAppService.bicep'

param appServiceName = 'chatbot-staging-001'
param appServicePlanName = 'plan-chatbot-staging-001'
param location = 'East US'
param appServicePlanSku = 'S1'
param dockerRegistryServerUrl = 'https://index.docker.io'
param dockerRegistryServerUsername = ''
param dockerRegistryServerPassword = ''
param mainAppImage = 'node:18-alpine'
param llmSidecarImage = 'ollama/ollama:latest'
param environment = 'staging'